/* tslint:disable */
/* eslint-disable */
/**
 * Oasis API
 * A booking system
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Reservation
 */
export interface Reservation {
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    startTime: number;
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    endTime: number;
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    resourceId: number;
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    customerId: number;
}

/**
 * Check if a given object implements the Reservation interface.
 */
export function instanceOfReservation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "startTime" in value;
    isInstance = isInstance && "endTime" in value;
    isInstance = isInstance && "resourceId" in value;
    isInstance = isInstance && "customerId" in value;

    return isInstance;
}

export function ReservationFromJSON(json: any): Reservation {
    return ReservationFromJSONTyped(json, false);
}

export function ReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reservation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startTime': json['start_time'],
        'endTime': json['end_time'],
        'resourceId': json['resource_id'],
        'customerId': json['customer_id'],
    };
}

export function ReservationToJSON(value?: Reservation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'start_time': value.startTime,
        'end_time': value.endTime,
        'resource_id': value.resourceId,
        'customer_id': value.customerId,
    };
}

