name: Generate OAS types

on:
  push:
    paths:
      - "postman/schemas/*.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Run generation
        run: |
          npm i @openapitools/openapi-generator-cli@2.5.2 --no-save 
          npm run generate-openapi-types
      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "generate OAS types"
